	yes,  we can have try without catch block by using finally block.
	You can use try with finally. 
	As you know finally block always executes even if you have exception or 
		return statement in try block except in case of System.exit().


	
	
 
		public class TryWithoutCatchMain {
 
		 public static void main(String args[]){

 		 	try{								//try block
  		 		System.out.println("Executing try block"); 
  				}	
 		 	finally{							// finally block
  		 		System.out.println("Executing finally block"); 
  			}
 		    }
		}